################################################################################
#
# Common Makefile for each test (Please include this file)
#
################################################################################

ifeq ($(origin SYSDEP_DIR), undefined)
   SYSDEP_DIR = $(TOPDIR)/sysdep
else
   ifeq ( "$(shell ls $(SYSDEP_DIR) | grep Makedef.$(SCALE_SYS))", "")
      SYSDEP_DIR=$(TOPDIR)/sysdep
   else
      USELOCALBIN = T
   endif
endif


include $(SYSDEP_DIR)/Makedef.$(SCALE_SYS)
include $(TOPDIR)/Mkinclude



msg1 = "\n"

ifeq ($(SCALE_DEBUG),T)
   msg1       += "SCALE_DEBUG is set.\n"
endif

ifeq ($(SCALE_USE_SINGLEFP),T)
   msg1       += "SCALE_USE_SINGLEFP is set.\n"
endif

ifneq ($(ORG_SRCS),)
   msg1       += "User-defined file is used.\n"
   USELOCALBIN = T
endif

ifeq ($(SCALE_DISABLE_LOCALBIN),T)
   USELOCALBIN = F
endif

ifeq ($(USELOCALBIN),T)
   BUILD_DIR := $(PWD)/.libs$(POSTFIX)
   BINDIR2    = $(PWD)
   msg1      += "The location of executable files is changed to $(BINDIR2)\n"
else
   BUILD_DIR = "undefined"
   BINDIR2   = $(BINDIR)
endif

ifeq ($(origin PPNAME), undefined)
   PPNAME = scale-rm_pp$(POSTFIX)
endif

ifeq ($(origin INITNAME), undefined)
   INITNAME = scale-rm_init$(POSTFIX)
endif

ifeq ($(origin BINNAME), undefined)
   BINNAME = scale-rm$(POSTFIX)
endif

ifeq ($(origin SNONAME), undefined)
   SNONAME = sno$(POSTFIX)
endif

ifeq ($(origin PPCONF), undefined)
   PPCONF = NONE
endif

ifeq ($(origin INITCONF), undefined)
   INITCONF = NONE
endif

ifeq ($(origin RUNCONF), undefined)
   RUNCONF = NONE
endif

ifeq ($(origin SNOCONF), undefined)
   SNOCONF = NONE
endif

ifeq ($(origin TPROC_SNO), undefined)
   TPROC_SNO = $(TPROC)
endif

UTILDIR    = ${TOPDIR}/scale-rm/util/sno


all: build


$(BUILD_DIR)/%.F90: $(CODE_DIR)/%.F90
	mkdir -p $(BUILD_DIR)
	cp -f $< $@

build: $(patsubst %,$(BUILD_DIR)/%,$(ORG_SRCS))
	@echo -e $(msg1)
	BUILD_DIR=$(BUILD_DIR) $(MAKE) -C $(SCALERMDIR)/src SYSDEP_DIR=$(SYSDEP_DIR) \
                                BINDIR=$(BINDIR2)

util:
	$(MAKE) -C $(UTILDIR)
	@if [ $(BINDIR2) != $(BINDIR) ]; then \
	  ln -s $(BINDIR)/$(SNONAME) $(BINDIR2)/$(SNONAME); \
	fi

run: jobshell
	$(JOBSUB) run.sh $(JOBSUB_OPTION)

jobshell:
	@if [ -f $(SYSDEP_DIR)/Mkjobshell.$(SCALE_SYS).sh ]; then \
		bash $(SYSDEP_DIR)/Mkjobshell.$(SCALE_SYS).sh $(MPIEXEC) $(BINDIR2)                        \
		                                              $(PPNAME) $(INITNAME) $(BINNAME) $(SNONAME) \
		                                              $(PPCONF) $(INITCONF) $(RUNCONF) $(SNOCONF) \
		                                              $(TPROC) $(TPROC_SNO)                       \
		                                              $(DATPARAM) $(DATDISTS);                    \
	else \
		bash $(TOPDIR)/sysdep/Mkjobshell.$(SCALE_SYS).sh $(MPIEXEC) $(BINDIR2)                     \
		                                              $(PPNAME) $(INITNAME) $(BINNAME) $(SNONAME) \
		                                              $(PPCONF) $(INITCONF) $(RUNCONF) $(SNOCONF) \
		                                              $(TPROC) $(TPROC_SNO)                       \
		                                              $(DATPARAM) $(DATDISTS);                    \
	fi

vis:
	bash ./visualize/visualize.sh

eval:
	bash ./evaluate/evaluate.sh

info:
	$(MAKE) -C $(SCALERMDIR)/src info \
	        BINDIR=$(BINDIR2)         \
          BUILD_DIR=$(BUILD_DIR)   \
          SYSDEP_DIR=$(SYSDEP_DIR)

.PHONY: allclean distclean clean

allclean: distclean clean
	$(MAKE) -C $(SCALERMDIR)/src allclean \
	        BINDIR=$(BINDIR2)         \
          BUILD_DIR=$(BUILD_DIR)   \
          SYSDEP_DIR=$(SYSDEP_DIR)

distclean: clean
	$(MAKE) -C $(SCALERMDIR)/src distclean \
	        BINDIR=$(BINDIR2)         \
          BUILD_DIR=$(BUILD_DIR)   \
          SYSDEP_DIR=$(SYSDEP_DIR)
	rm -f *.nc *LOG.pe* monitor.pe* latlon* run.sh *.png

clean:
	$(MAKE) -C $(SCALERMDIR)/src clean \
	        BINDIR=$(BINDIR2)         \
          BUILD_DIR=$(BUILD_DIR)   \
          SYSDEP_DIR=$(SYSDEP_DIR)

