export RECUPEROMAP=(
"00"      #Miembro con que se recupera al 00
"02"      #Miembro con que se recupera al 01
"03"      #Miembro con que se recupera al 02
"10"      #Miembro con que se recupera al 03
"05"      #Miembro con que se recupera al 04
"06"      #Miembro con que se recupera al 05
"24"      #Miembro con que se recupera al 06
"08"      #Miembro con que se recupera al 07
"09"      #Miembro con que se recupera al 08
"17"      #Miembro con que se recupera al 09
"21"      #Miembro con que se recupera al 10
"12"      #Miembro con que se recupera al 11
"13"      #Miembro con que se recupera al 12
"31"      #Miembro con que se recupera al 13
"15"      #Miembro con que se recupera al 14
"16"      #Miembro con que se recupera al 15
"04"      #Miembro con que se recupera al 16
"18"      #Miembro con que se recupera al 17
"19"      #Miembro con que se recupera al 18
"20"      #Miembro con que se recupera al 19
"37"      #Miembro con que se recupera al 20
"22"      #Miembro con que se recupera al 21
"23"      #Miembro con que se recupera al 22
"30"      #Miembro con que se recupera al 23
"25"      #Miembro con que se recupera al 24
"26"      #Miembro con que se recupera al 25
"27"      #Miembro con que se recupera al 26
"28"      #Miembro con que se recupera al 27
"29"      #Miembro con que se recupera al 28
"07"      #Miembro con que se recupera al 29
"11"      #Miembro con que se recupera al 30
"32"      #Miembro con que se recupera al 31
"33"      #Miembro con que se recupera al 32
"34"      #Miembro con que se recupera al 33
"35"      #Miembro con que se recupera al 34
"36"      #Miembro con que se recupera al 35
"14"      #Miembro con que se recupera al 36
"38"      #Miembro con que se recupera al 37
"39"      #Miembro con que se recupera al 38
"40"      #Miembro con que se recupera al 39
"01"      #Miembro con que se recupera al 40
)
