function [maxterrainheight]=get_terrain_data(radar,terrain)

% This function gets a digital elevation model and interpolates
% the data to the radar grid at each radar level (each radar level has its
% own grid).
% The terrain data has to be provided by the terrain structure that must
% contain terrain.height, terrain.lon and terrain.lat the terrain heigth
% matrix and their corresponding lon and lat matrices. (a regular lat lon
% grid for the terrain data is assumed, however the function can be easily
% generalized replacing interp2 function by griddata);
% Radar struture must contain radar.lon and radar.lat for each vertical
% level. These fields are generated by the georeference_radar_data
% function.
% Terrain relative height can then be easily obtained as
% radar.Z-maxterrainheigth.
% 
% 
% By Juan Ruiz 2014

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Interpolate terrain data.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%We will interpolate using bilinear interpolation since the terrain data has
%already been interpolated to a grid closer in resolution to the one used by
%the radar.
tic

 [maxterrainheight]=fast_interp_2d(radar,terrain.maxheight,terrain.lon,terrain.lat);

 time=toc;
 
 display(['Terrain data is interpolated in ' num2str(time) ' seconds'])


